# Generated by Django 4.0.2 on 2022-06-30 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(default=datetime.date(2010, 1, 1), verbose_name='Birthdate'),
        ),
    ]
