# Generated by Django 4.0.5 on 2022-06-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Please enter your Email...', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
